routes/web.php
<?php

use App\Http\Controllers\AcademicCouncilController;
use App\Http\Controllers\AdminCouncilController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FilesController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\PreboardMeetingController;
use App\Http\Controllers\RegularBoardMeetingController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\SpecialMeetingController;
use App\Http\Controllers\Superadmin\CategoryController;
use App\Http\Controllers\Superadmin\DashboardController as SuperadminDashboardController;
use App\Http\Controllers\Superadmin\DocumentTypeController;
use App\Http\Controllers\Superadmin\UsersController as SuperadminUsersController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/* Route::get('/', [IndexController::class, 'index'])->name('home'); */
Route::get('/index', [IndexController::class, 'index'])->name('index');

Route::post('/index', [AuthController::class, 'login'])->name('login');


/* Admin */
Route::prefix('admin')->name('admin.')->group(function(){

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/d',[DashboardController::class, 'getData'])->name('get.meetingTotals');
    Route::get('/getCategory/{id}', [CategoryController::class,'fetch']);
    Route::post('/dashboard', [DashboardController::class, 'store'])->name('store.meetingDetails');
    

    Route::controller(AdminCouncilController::class)->group(function(){
        Route::get('/admincouncil', 'index')
            ->name('admin-council.index');
        Route::get('/adminCouncilCreate/{id}', 'create')
            ->name('admin-council.create');
        Route::post('/adminCouncilCreate', 'store')
            ->name('admin-council.store');
        Route::get('/adminCouncilEdit/{id}','edit')
            ->name('admin-council.edit');
        Route::post('/adminCouncilUpdate', 'update')
            ->name('admin-council.update');
        Route::delete('/adminCouncilDelete/{id}','destroy')
            ->name('admin-council.destroy');
        Route::get('/adminCouncilDownload/{id}', 'download')
            ->name('admin-council.download');
        Route::get('/adminCouncilMeetingDetails/{id}', 'meetingDetails')
            ->name('admin-council.meeting-details');
    });

    Route::controller(AcademicCouncilController::class)->group(function(){
        Route::get('/AcademicCouncil', 'index')
            ->name('academic-council.index');
        Route::get('/AcademicCouncilCreate/{id}', 'create')
            ->name('academic-council.create');
        Route::post('/AcademicCouncilCreate', 'store')
            ->name('academic-council.store');
        Route::get('/AcademicCouncilEdit/{id}', 'edit')
            ->name('academic-council.edit');
        Route::post('/AcademicCOuncilUpdate', 'update')
            ->name('academic-council.update');
        Route::delete('/AcademicCouncilDelete/{id}', 'destroy')
            ->name('academic-council.destroy');
        Route::get('/AcademicCouncilMeetingDetails/{id}', 'meeting')
            ->name('academic-council.meeting-details');
        Route::get('/AcademicCouncilDownload/{id}', 'download')
            ->name('academic-council.download');
    });
    
    /* Academic Council -> Remove File Uploaded */
    Route::post('/updateAcademic', [AcademicCouncilController::class,'remove'])->name('remove.academiccouncil');

    Route::controller(PreboardMeetingController::class)->group(function(){
        Route::get('/PreboardMeeting', 'index')
            ->name('preboard-meeting.index');
        Route::get('/PreboardMeetingCreate/{id}', 'create')
            ->name('preboard-meeting.create');
        Route::post('/PreboardMeetingStore', 'store')
            ->name('preboard-meeting.store');
        Route::get('/PreboardMeetingEdit/{id}', 'edit')
            ->name('preboard-meeting.edit');
        Route::post('/PreboardMeetingUpdate', 'update')
            ->name('preboard-meeting.update');
        Route::delete('/PreboardMeetingDestroy/{id}', 'destroy')
            ->name('preboard-meeting.destroy');
        Route::get('/PreboardMeetingMeetingDetails/{meeting_details}', 'meeting')
            ->name('preboard-meeting.meeting-details');
        Route::get('/PreboardMeetingDownload/{id}', 'download')
            ->name('preboard-meeting.download');
    });

    Route::controller(RegularBoardMeetingController::class)->group(function () {
        Route::get('/RegularBoardMeeting', 'index')
            ->name('regular-board-meeting.index');
        Route::get('/RegularBoardMeetingCreate/{id}', 'create')
            ->name('regular-board-meeting.create');
        Route::post('/RegularBoardMeetingStore', 'store')
            ->name('regular-board-meeting.store');
        Route::get('/RegularBoardMeetingEdit/{meeting_details}', 'edit')
            ->name('regular-board-meeting.edit');
        Route::post('/RegularBoardMeetingUpdate', 'update')
            ->name('regular-board-meeting.update');
        Route::delete('/RegularBoardMeetingDestroy/{id}', 'destroy')
            ->name('regular-board-meeting.destroy');
        Route::get('/RegularBoardMeetingMeetingDetails/{id}', 'meeting')
            ->name('regular-board-meeting.meeting-details');
        Route::get('/RegularBoardMeetingDownload/{id}', 'download')
            ->name('regular-board-meeting.download');
            
    });

    Route::controller(SpecialMeetingController::class)->group(function () {
        Route::get('/SpecialMeeting', 'index')
            ->name('special-meeting.index');
        Route::get('/SpecialMeetingCreate/{id}', 'create')
            ->name('special-meeting.create');
        Route::post('/SpecialMeetingStore', 'store')
            ->name('special-meeting.store');
        Route::get('/SpecialMeetingEdit/{meeting_details}', 'edit')
            ->name('special-meeting.edit');
        Route::post('/SpecialMeetingUpdate', 'update')
            ->name('special-meeting.update');
        Route::delete('/SpecialMeetingDestroy/{id}', 'destroy')
            ->name('special-meeting.destroy');

        Route::get('/SpecialMeetingMeetingDetails/{meeting_details}', 'meeting')
            ->name('special-meeting.meeting-details');
        Route::get('/SpecialMeetingMeetingDownload/{id}', 'download')
            ->name('special-meeting.download');
    });

    Route::controller(UsersController::class)->group(function () {
        Route::get('/UserAccount', 'index')
            ->name('user-account.index');
        Route::put('/UserAccount/{user_account}', 'update')
            ->name('user-account.update');
    });

    Route::controller(ReportsController::class)->group(function () {
        Route::get('/reports', 'index')
            ->name('reports.index');
        Route::get('/ViewReports/{id}', 'viewReports')
            ->name('view-reports.view-reports');
        Route::post('/ViewReports', 'fetchData')
            ->name('view-reports.reports');
        Route::get('/filter', 'filter_year')
            ->name('filter_year.reports');
        Route::post('/printPDF', 'print_pdf')
            ->name('print_pdf.reports');
    });

    Route::controller(FilesController::class)->group(function () {
        Route::get('/Files/{meeting_details}', 'index')
            ->name('files.index');
        Route::get('/Files/{id}/Add_File', 'add_files')
            ->name('files.add-files');
        Route::post('/Files/store', 'store')
            ->name('files.store');
        Route::get('/FilesDownload/{id}', 'download')
            ->name('files.download');
        Route::delete('/DeleteFiles/{id}', 'destroy')
            ->name('files.destroy');
    });

  
});



/* Superadmin */

Route::prefix('superadmin')->name('superadmin.')->group(function(){
    
    Route::get('/dashboard', [SuperadminDashboardController::class, 'index'])->name('index.dashboard');

    /* Category */

    Route::get('/manageCategory', [CategoryController::class, 'index'])->name('index.category');
    Route::get('/createCategory', [CategoryController::class, 'create'])->name('create.category');
    Route::post('/createCategory', [CategoryController::class, 'store'])->name('store.category');

    /* Document Type */

    Route::get('/manageDocumentType', [DocumentTypeController::class, 'index'])->name('index.documenttype');
    Route::get('/createDocumentType', [DocumentTypeController::class, 'create'])->name('create.documenttype');
    Route::post('/createDocumentType', [DocumentTypeController::class, 'store'])->name('store.documenttype');
    Route::get('/{id}/updateDocumentType', [DocumentTypeController::class,'edit'])->name('edit.documenttype');
    Route::put('/{id}/updateDocumentType', [DocumentTypeController::class,'update'])->name('update.documenttype');

    /* Users Management */
    Route::get('/users', [SuperadminUsersController::class, 'index'])->name('index.users');
    Route::get('/createUsers', [SuperadminUsersController::class,'create'])->name('create.users');
    Route::post('/createUsers', [SuperadminUsersController::class,'store'])->name('store.users');
    Route::get('/{id}/updateUsers', [SuperadminUsersController::class, 'edit'])->name('edit.users');

});

/* Logout */

Route::get('/', [AuthController::class, 'logout'])->name('logout');

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'file_path'
    ];
}

app/Http/Controllers/FilesController.php
<?php

namespace App\Http\Controllers;

use App\Models\DocumentFiles;
use App\Models\File;
use App\Models\MeetingDetails;
use App\Models\Superadmin\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;
use League\CommonMark\Node\Block\Document;

class FilesController extends Controller
{
    //
    public function index(MeetingDetails $meeting_details){
      /*  dd($meeting_details); */
        $document_files = DocumentFiles::where('meeting_details_id', $meeting_details->id)->get();
        $category = MeetingDetails::join('category', 'category.id','=','meeting_details.category_id')
        ->where('meeting_details.id', $meeting_details->id)->first('category.categoryName');

        if($document_files->count()){
            foreach($document_files AS $df){
                $files[] = File::WHERE('id', $df->file_id)->get();
                
            }
            
        }else{
            $files = [];
        }

       /*  dd($files); */
        return view('pages.admin.files.index',[
            'files' => $files,
            'meeting_details' => $meeting_details,
            'category' => $category->categoryName,
        ]);
    }

    public function add_files(string $id){
    
        return view('pages.admin.files.add-files',[
            'meeting_details_id' => $id,
          
        ]);
    }

    public function store(Request $request){
        $data = MeetingDetails::join('category', 'category.id','=','meeting_details.category_id')
            ->where('meeting_details.id', $request->id)->first();
            
        if($data->categoryName == 'Admin Council'){
            $fileNamePrefix = 'admincouncil_'.$data->document_type;
        }elseif($data->categoryName == 'Academic Council'){
            $fileNamePrefix = 'academiccouncil_'.$data->document_type;
        }elseif($data->categoryName == 'Preboard Meeting'){
            $fileNamePrefix = 'preboard_'.$data->document_type;
        }elseif($data->categoryName == 'Regular Board Meeting'){
            $fileNamePrefix = 'regularboard_'.$data->document_type;
        }elseif($data->categoryName == 'Special Meeting'){
            $fileNamePrefix = 'specialmeeting_'.$data->document_type;
        }

        foreach($request->file AS $files){
            $agenda_file_name = $fileNamePrefix.'_'.$files->getClientOriginalName();
            $path_file = $files->storeAs('public/uploads', $agenda_file_name);
            $files = File::create([
                'name' => $agenda_file_name,
                'file_path' => $path_file,
            ]);

            $files_id[] = $files->id;
        }

        foreach($files_id as $id){
            DocumentFiles::create([
                'meeting_details_id' => $request->id,
                'file_id' => $id,
            ]);
        }

        return redirect()->route('admin.files.index', ['meeting_details' => $request->id]);
        

    }

    public function download(string $id){
        
        $stmt = File::where('id', $id)->first();
        $data = Storage::get($stmt->file_path);
        
        $response = Response::make($data, 200);
        $response->header('Content-Type', 'application/pdf');
        return $response;
    }

    public function destroy(string $id){
        /* dd($id); */
        $file = File::where('id', $id)->first();
        Storage::delete($file->file_path);
        File::where('id', $id)->delete();

        $document_files = DocumentFiles::where('file_id', $id)->first();
        $meeting_details_id = $document_files->meeting_details_id;
        DocumentFiles::where('file_id',$id)->delete();

        return redirect()->route('admin.files.index', ['meeting_details' => $meeting_details_id])->with('success', 'Delete Successful');
    }
}

resources/views/pages/admin/files/add-files.blade.php
@extends('pages.admin.layout.layout')
@section('title', 'DMS-Dashboard')
@section('content')
<div class="container-fluid">
 
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <!-- Card -->
        <div class="card mb-3">
          <div class="card-header" style="background-color: transparent; text-align:center;">
              <div class="row">
                <div class="col-md-2 text-center d-flex align-items-center justify-content-center">
                  <img src="{{ asset('img/Bagong_Pilipinas_logo.png') }}" alt="" width="75px;" height="70px;" class="p-0">
                  
                </div>
                <div class="col-md-8 text-center d-flex align-items-center justify-content-center">
                  <h2><strong>ADD FILES</strong></h2>
                </div>
                <div class="col-md-2 text-center d-flex align-items-center justify-content-center">
                  <img src="{{ asset('img/dmmmsu_logo.png') }}" alt="" width="75px;" height="70px;" class="p-0">
                </div>
              </div>
          </div>
        </div>


      <div class="card ">
        <div class="card card-header" style="background-color: transparent;">
          <div class="d-flex justify-content-end align-items-center">
            <a href="{{ route('admin.files.index', ['meeting_details' => $meeting_details_id ]) }}">
              <x-button-primary>Back</x-button-primary>
            </a>
          </div>
        </div>
        
        <div class="card-body">
          <div class="mt-2">
            @if (session()->has('success'))
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ session('success') }}
              </div>
            @elseif (session()->has('error'))  
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ session('error') }}
              </div>
            @else
              
            @endif
          </div>
          

          <form action="{{ route('admin.files.store') }}" method="post" enctype="multipart/form-data" >
            @csrf
            <input type="hidden" name="id" id="id" value="{{ $meeting_details_id }}">
            <div class="row mb-3">
              <label for="" class="col-md-3 col-form-label">File:
                <a id="add_file_upload" class="btn btn-success rounded-pill p-1">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:25px; height:25px;">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                  </svg>
                </a>
              </label>
              <div class="col-md-9" id="file_container">
                  <input type="file" name="file[]" id="file[]" class="form-control mb-3">
              </div>
            </div>
            <div class="row mb-3 ">
              <div class="col-md-12 justify-content-center ">
                <div class="row justify-content-center">
                    <button type="submit" class="btn btn-success rounded-pill" style="width: 120px;" id="submit">Submit</button>
                    <button type="reset" class="btn btn-danger rounded-pill" style="width: 120px;">Reset</button>
                </div>
              </div>

            </div>

          </form>
        </div>
      </div>
      <!-- Card -->
    </div>
    <div class="col-md-2"></div>
  </div>

</div>

@endsection
@section('script')
  <script>
    // SideNav Initialization
    $(".button-collapse").sideNav();

    let container = document.querySelector('.custom-scrollbar');
    var ps = new PerfectScrollbar(container, {
        wheelSpeed: 2,
        wheelPropagation: true,
        minScrollbarLength: 20
    });
  

    const file_container = document.getElementById('file_container')
    document.getElementById('add_file_upload').addEventListener('click', function(){
        const child = document.createElement('input')
        child.setAttribute('type', 'file')
        child.setAttribute('name', 'file[]')
        child.setAttribute('class', 'form-control mb-3')
        file_container.appendChild(child)
    });

      /* const agenda_container = document.getElementById('agenda_container')
      document.getElementById('add_agenda_upload').addEventListener('click', function(){
          const child = document.createElement('input')
          child.setAttribute('type', 'file')
          child.setAttribute('name', 'agenda[]')
          child.setAttribute('class', 'form-control')
          agenda_container.appendChild(child)
      });

      const resolution_container = document.getElementById('resolution_container')
      document.getElementById('add_resolution_upload').addEventListener('click', function(){
          const child = document.createElement('input')
          child.setAttribute('type', 'file')
          child.setAttribute('name', 'resolution_file[]')
          child.setAttribute('class', 'form-control')
          resolution_container.appendChild(child)
      });

      const minutes_container = document.getElementById('minutes_container')
      document.getElementById('add_minutes_upload').addEventListener('click', function(){
        const minutes_child = document.createElement('input')
        minutes_child.setAttribute('type', 'file')
        minutes_child.setAttribute('name', 'minutes_file[]')
        minutes_child.setAttribute('class', 'form-control')
        minutes_container.appendChild(minutes_child)
      
      });

      const attendance_container = document.getElementById('attendance_container')
      document.getElementById('add_attendance_upload').addEventListener('click', function(){
        const attendance_child = document.createElement('input')
        attendance_child.setAttribute('type', 'file')
        attendance_child.setAttribute('name', 'attendance_file[]')
        attendance_child.setAttribute('class', 'form-control')
        attendance_container.appendChild(attendance_child)
      });

      const memo_container = document.getElementById('memo_container')
      document.getElementById('add_memo_upload').addEventListener('click', function(){
        const memo_child = document.createElement('input')
        memo_child.setAttribute('type', 'file')
        memo_child.setAttribute('name', 'memo_file[]')
        memo_child.setAttribute('class', 'form-control')
        memo_container.appendChild(memo_child)
      });  */

  </script>
@endsection

    


  

  

resources/views/pages/admin/files/index.blade.php
@extends('pages.admin.layout.layout')
@section('title', 'DMS-Dashboard')
@section('content')

    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2 text-center d-flex align-items-center justify-content-center">
                      <img src="{{ asset('img/Bagong_Pilipinas_logo.png') }}" alt="" width="75px;" height="70px;" class="p-0">
                      
                    </div>
                    <div class="col-lg-8 text-center d-flex align-items-center justify-content-center">
                        <div class="row">
                            <h2><strong>{{ $category }}</strong></h2>
                        </div>
                    </div>
                    <div class="col-md-2 text-center d-flex align-items-center justify-content-center">
                      <img src="{{ asset('img/dmmmsu_logo.png') }}" alt="" width="75px;" height="70px;" class="p-0">
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" style="background-color: transparent;">
                <div class="d-flex align-items-center justify-content-end">
                    @if ($category == 'Admin Council')
                        <a href="{{ route('admin.admin-council.index') }}">
                            <x-button-primary>Back</x-button-primary>
                        </a>
                    @elseif ($category == 'Academic Council')
                        <a href="{{ route('admin.academic-council.index') }}">
                            <x-button-primary>Back</x-button-primary>
                        </a>
                    @elseif ($category == 'Preboard Meeting')
                        <a href="{{ route('admin.preboard-meeting.index') }}">
                            <x-button-primary>Back</x-button-primary>
                        </a>
                    @elseif ($category == 'Regular Board Meeting')
                        <a href="{{ route('admin.regular-board-meeting.index') }}">
                            <x-button-primary>Back</x-button-primary>
                        </a>
                    @elseif ($category == 'Special Meeting')
                        <a href="{{ route('admin.special-meeting.index') }}">
                            <x-button-primary>Back</x-button-primary>
                        </a>
                    @endif

                    
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <strong>Document Type:</strong> {{ $meeting_details->document_type }}
                    </div>
                    <div class="col-md-12">
                        <strong>Document Description:</strong> {{ $meeting_details->document_type }}
                    </div>
                </div>
            </div>
           <div class="card-body">
                <div class="d-flex align-items-center justify-content-end mb-3 mr-3">
                    <a href="{{ route('admin.files.add-files', ['id' => $meeting_details->id]) }}">
                        <button class="btn btn-success rounded-pill p-2">
                            <strong>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:20px; height: 20px;">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                                </svg>
                            </strong>
                        </button>
                    </a>
                </div>
                <table id="dtMaterialDesignExample" class="table table-striped" cellspacing="0" width="100%">
                    <tbody>
                        @if ($files == null)
                            <tr>
                                <td colspan="3">No Data Available</td>
                            </tr>
                        @else
                            
                        @endif
                        @foreach ($files as $item)
                            @foreach ($item as $items)
                                <tr>
                                    
                                    <td>{{ $items->name }}</td>
                                    <td>
                                        <a href="{{ route('admin.files.download', ['id' => $items->id]) }}">
                                            <button class="btn btn-success rounded-pill p-2">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:20px; height: 20px;">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                                  </svg>
                                                  
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a data-toggle="modal" data-target="#delete{{ $items->id }}">
                                            <button class="btn btn-danger rounded-pill p-2">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width:20px; height: 20px;">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                                </svg>
                                            </button>
                                        </a>
                                        <div class="modal fade" id="delete{{ $items->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                                            aria-hidden="true">
                                            <div class="modal-dialog modal-notify modal-info" role="document">
                                              <!-- Content -->
                                              <div class="modal-content">
                                                <!-- Header -->
                                                <div class="modal-header" style="background-color: #16a34a; ">
                                                  <p class="heading lead text-center">Delete File</p>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true" class="white-text">&times;</span>
                                                  </button>
                                                </div>
                      
                                                <!-- Body -->
                                                <div class="modal-body">
                                                               
                                                  Do you really want to delete these records? This process cannot be undone.
                                                  <form action="{{ route('admin.files.destroy', ['id' => $items->id ]) }}" method="post">
                                                    @method('delete')
                                                    @csrf
                                                </div>
                      
                                                <!-- Footer -->
                                                <div class="modal-footer justify-content-center">
                                                  <button type="submit" class="btn btn-outline-danger waves-effect" >Delete</button>
                                                  <button type="button" class="btn btn-outline-success waves-effect" data-dismiss="modal">Close</button>
                                                </div>
                                                  </form>
                                              </div>
                                              <!-- Content -->
                                            </div>
                                          </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endforeach
                    </tbody>
                </table>
           </div>
        </div>
    </div>
@endsection
@section('script')
  
@endsection

resources/views/pages/admin/files/upload.blade.php
@extends('pages.admin.layout.layout')
@section('title', 'DMS-Dashboard')
@section('content')
    <div class="container-fluid">
        
    </div>
@endsection
@section('script')
  
@endsection